openapi: 3.0.3
info:
  title: My API
  description: This is a simple API.
  version: 1.0.0
servers:
  - url: http://localhost:8080/udemy/api/genshin
paths:
  /players:
    get:
      summary: Get all Players.
      responses:
        200:
          description: A list of Players.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
  /customers/{id}:
    get:
      summary: Get a customer by ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: The customer with the specified ID.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        404:
          description: Customer not found.
components:
  schemas:
    Customer:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string